apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-https-route
spec:
  parentRefs:
  - name: gateway
    sectionName: https-www-luisito-dev
    namespace: operations
  hostnames:
  - www.luisito.dev
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: portfolio
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-https-route
spec:
  parentRefs:
  - name: gateway
    sectionName: https-luisito-dev
    namespace: operations
  hostnames:
  - luisito.dev
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: portfolio
      port: 80